config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'una', to: 'pages#una'
  get 'utero', to: 'pages#utero'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def picto(this_path)
  #   test = this_path
  #   case test
  #   when "/"
  #     puts "Levanta-Zabele_Logo-Picto.png"
  #   when "/utero"
  #   end
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def una
  end

  def utero
  end

  # @test = request.path
  # def picto ()
  #   case @test
  #   when "/"
  #     puts "Levanta-Zabele_Logo-Picto.png"
  #   when "/utero"
  #     puts "Levanta-Zabele_Logo-Picto.png"
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# <meta name="turbolinks-root" content="/app"> %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%# <%= javascript_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main-container">
  <%# iniciate responsivness %>
  <div class="levanta-zabele row">
    <%= image_tag "Levanta-Zabele_Logo.png" %>
  </div>

  <div class="banner-1">
      <%= link_to "/una" do %>
        <%= image_tag "Una_Banner-floater.png" %>
      <% end %>
  </div>

  <div class="container-2 ">
    <div class="row row-centered pos">
      <%= image_tag "Somos_Titulo.png" %>
    </div>
    <div class="who-are-we">
      <div class="fonts-1">
        <p>Levanta Zabelê é um núcleo de projetos interculturais.</p>
      </div>
      <div class="fonts-2">
        <p><b>Uma rede de colaboradores</b> do Brasil e do mundo que envolve profissionais, pesquisadores, ativistas, educadores, artistas, artesãos; de variadas origens, culturas e áreas do conhecimento. Juntos, formamos um corpo, orgânico. Um ser-coletivo.
        <p>Com origem indígena, o Levanta Zabelê é uma rede aberta, diversa e realizadora de projetos que promovem experiências de aprendizagem viva com troca de saberes, expressões artísticas, convivências e interações com a Natureza.</p>
        <p>Também integram a rede Levanta Zabelê empresas, entidades e organização civis apoiadoras que compartilham nossos propósitos e contribuem com a realização
          e evolução de nossa sociedade e o planeta.</p>
      </div>
    </div>
  </div>

  <div class="banner-2">
    <div class="row">
      <%= image_tag "Essencia-Originaria.png" %>
    </div>
    <div class="fonts-3">
      <p>“Nós, Povos da Floresta, vivenciamos essa transcendência. Sabemos da importância de estarmos ligados
    a outros elementos essenciais à vida.
    Fazemos parte de um todo”.</p>
    <%= image_tag "Yakuy_Monograma.png" %>
    </div>
  </div>

  <div class="container-3">
    <div class="yakuy">
      <%= image_tag "Yakuy_Titulo.png" %>
      <p style="font-size: large"><b>Yakuy Tupinambá, origem do Útero.</b></p>
      <p>Da comunidade Tupinambá de Olivença/ Bahia, palestrante na ABL (Academia Brasileira de Letras), junto ao filósofo italiano Gianni Vattimo, em 2008, atuante no evento mídias nativas (São Paulo, em 2007 e 2009). Docente
      no Curso de Extensão em filosofia indígena, Escutar o Outro na Faculdade de Letras da UFRJ em 2010. Pensadora indígena, escritora, comunicadora e idealizadora do Levanta Zabelê e do Universo Intercultural de Saberes Útero Amotara Zabelê.</p>
    </div>
    <div id="yakuy-pic">
    </div>
  </div>

  <div class="banner-3">
    <%= image_tag "Utero_Circulos.png" %>
    <div class="fonts-1">
      <p><b>Nossas ideias e projetos tem uma origem: <span style="color: #ec1846">o Útero</span></b>.</p>
      <p>Conheça nosso propósito e os conceitos que nos movem.</p>
    </div>
  </div>

  <div class="container-4">
    <div class="realizamos">
      <%= image_tag "Realizamos_Titulo.png" %>
      <div class="fonts-5">
        <p><b style="color: white; font-size: 1.4rem">Desenvolvemos projetos educativos e interculturais</b>
        de variados temas envolvendo mutirões comunitários, fomento de economia sustentável na comunidade tupinambá de Una, onde está localizado o Universo Útero,
        produções artísticas (musicais e audiovisuais), acadêmicas e literárias,
        geração e difusão de conteúdos.</p>
        <p>Veja abaixo alguns projetos e ações realizadas pelo coletivo Levanta Zabelê.</p>
      </div>
    </div>
    <div class="table-projects">
      <table>
        <tr>
            <td><%= image_tag "Movimenta_Box-Una.png" %></td>
            <td id='greenFont'>Universo Autônomo Intercultural de Saberes Útero Amotara Zabelê.</td>
            <td id='white'><p>Espaço de vivência de educação viva localizado no sul da Bahia.</p>
            <p>Atualmente estamos na fase de construção e captação de recursos. Conheça mais sobre o Universo
            Útero e contribua com sua realização.</p></td>
        </tr>
        <tr>
            <td><%= image_tag "mascara.jpg" %></td>
            <td id='redFont'>Mantrifesto Utero</td>
            <td id='red'>Universo Autônomo Intercultural de Saberes Útero Amotara Zabelê.</td>
        </tr>
        <tr>
            <td id='imgforce'></td>
            <td id='orangeFont'>Projeto Loja Colaborativa do Levanta Zabelê</td>
            <td id='orange'><p>Estamos desenvolvendo o projeto da loja virtual
            do Levanta Zabelê com envolvimento das comunidades tupinambá de Una.</p>
            <p>O projeto inlcui oficinas e cursos profissionalizantes para capacitação de jovens-aprendizes, que serão
            os protagonistas na administração, gestão e operação da loja. Em breve mais novidades aqui no site e
            nas redes sociais do Zabelê</p></td>
        </tr>
      </table>
    </div>
    <div class="movimenta">
      <%= image_tag "Movimenta_Picto-G.png", style: "height:10rem" %>
      <%= image_tag "MovimentaZabele_Tipo.png", style: 'height:7rem' %>
      <div class="realizamos-2">
        <p>Fique por dentro de nossos projetos e atividades</p>
        <%= image_tag "Flecha_Picto.png", style: 'height:2rem' %>
      </div>
    </div>
  </div>

  <div class="container-5">
    <div class="net">
      <%= image_tag "Rede_Titulo.png" %>
      <p>Conheça nossos apoiadores e parceiros que estão juntos nessa jornada, fazendo acontecer.</p>
    </div>
    <div class="partners">
      <%= image_tag "Rede_Serbrand.png" %>
      <%= image_tag "Rede_AladoEnergy.png" %>
      <%= image_tag "Rede_UFSB.png" %>
      <%= image_tag "Rede_Visibilidade.png" %>
    </div>
    <div class="partners">
      <%= image_tag "Rede_Originarias.png" %>
      <%= image_tag "Rede_Macieira.png" %>
      <%= image_tag "Rede_PelasMulheresIndigenas.png" %>
      <%= image_tag "Rede_PlataformaArquitetura.png" %>
    </div>
    <div class="partners">
      <%= image_tag "Rede_FundSaborNatureza.png" %>
      <%= image_tag "Rede_Transcriativa.png" %>
      <%= image_tag "Rede_BND.png" %>
    </div>
  </div>

</div>

app/views/pages/una.html.erb
<div class="main-container">

  <div class="universo-una">
    <%= image_tag "Universo-Una_Logo.png" %>
  </div>

  <div class="floresta-banner">
    <p id='escola'>Uma escola para a</p>
    <p id='vida'>vida.</p>
  </div>

  <div class="container-universo-una">
    <%= image_tag "Universo-Una_Logo-Selo.png" %>
    <div class="inivero-autonomo">
      <div class="fonts-una-green">
        <p>O Universo Autônomo Intercultural de Saberes • Útero Amotara Zabelê, é um espaço educativo de responsabilidade multiétnica.</p>
      </div>
      <div class="fonts-2">
        <p>É organizado pelo coletivo Levanta Zabelê com apoio de um grupo de profissionais de várias áreas do conhecimento e representantes da comunidade local, juntos em busca de realizar um espaço educativo livre, autônomo e aberto para propostas de educação alternativas.</p>
        <b>Um espaço para diálogo, geração de conhecimento, aprendizado e experiências mútuas de interação entre diversas culturas, saberes e fazeres.</b>
      </div>
    </div>
  </div>

  <div class="utero-amontara-container">
    <div class="fonts-utero-amontara">
      <p>Localizado em um ecossistema preservado e com grande biodiversidade,
      permite experiências educacionais envolvendo práticas, métodos e conhecimentos compartilhados, contando com um epaço amplo para realização de atividades
      e infra-estrutura para hospedagem.</p>
    </div>
    <%= image_tag "Universo-Una_Nucleos.png" %>
  </div>

  <div class="local">
    <div class="local-carrosel">
      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "Espaco-0.jpg", class: "d-block w-100" %>
            <%# <img src="Espaco-2.jpg" class="d-block w-100" alt="..."> %>
            <div class="carousel-caption d-none d-md-block">
              <%# <h5>First slide label</h5>
              <p>Some representative placeholder content for the first slide.</p> %>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-1.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-2.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-3.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-4.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-5.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-6.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-7.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-8.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-9.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-10.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag "Espaco-11.jpg", class: "d-block w-100" %>
            <div class="carousel-caption d-none d-md-block">

            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="description">
      <p>Local onde será construído o Universo Autônomo Intercultural de Saberes • Útero Amotara Zabelê. no sul da Bahia.</p>
    </div>
  </div>


  <div class="container-purpose">
    <div class="purpose">
      <%= image_tag "Proposito_Titulo.png" %>
      <div class="font-purpose">
        <p><b>Vivenciar, respeitar e valorizar a pluralidade etno-cultural do Planeta.</b></p>
        <p>Com temas indígenas, ambientais, científicos, socioculturais, de diferentes vertentes e povos, uniremos pessoas com pontos de vista diferentes para refletirem, repensarem, reavaliarem conceitos e ideias para juntos alcançarmos novos consensos.</p>
        <p>Queremos preencher o vácuo histórico da polarização de ideias, desconstruir mitos que reforçam as desigualdades, expandir nossos sentidos, pensamentos e contribuir para um caminho de evolução conjunta da humanidade, que recupere nossa comunhão uns com os outros e com a Mãe Natureza.</p>
      </div>
    </div>
    <div class="separador">
      <%= image_tag "Fios-separador-verde.png" %>
    </div>
    <div class="purpose">
      <%= image_tag "Objetivos_Titulo.png" %>
      <div class="font-purpose">
        <p><b>Promover vivências, ciclos de debates e oficinas</b>com temáticas variadas, que abordam questões sobre a realidade, as sociedades, culturas, o futuro da humanidade e do planeta Terra, integrando conhecimentos ancestrais e contemporâneos, povos e cultura diversas, saberes científicos e populares.</p>
        <p><b>Desenvolver-se como núcleo de valorização e resgate das culturas e línguas originárias</b> brasileiras e de outros povos do mundo, envolvendo comunidades locais e de outras regiões nas atividades.</p>
        <p><b>Sistematizar encontros com escolas das redes pública e particular</b> para que docentes e discentes vivenciem as experiências de cada uma das células ativas.</p>
      </div>
    </div>
    <div class="separador">
      <%= image_tag "Fios-separador-verde.png" %>
    </div>
    <div class="purpose">
      <%= image_tag "Atividades_Titulo.png" %>
      <div class="font-purpose">
        <p>No Universo Útero, realizamos oficinas, encontros, vivências, workshops, eventos, ações comunitárias, atividade recreativas e culturais, entre outras; evolvendo visitantes e a comunidade tupinambá local.</p>
        <p>A própria construção das malocas e casas fazem parte das atividades de integração entre o coletivo Levanta Zabelê, a comunidade local e nossos apoiadores.</p>
        <p>Também as oficinas de aprendizagem de artesanato e produção
            de produtos que estão disponíveis para venda nas redes do Levanta Zabelê.</p>
      </div>
    </div>
    <div class="separador">
      <%= image_tag "Fios-separador-verde.png" %>
    </div>
  </div>

  <div class="local">
    <div class="local-carrosel">
      <%= image_tag "Espaco-2.jpg" %>
    </div>
    <div class="description">
      <p>Local onde será construído o Universo Autônomo Intercultural de Saberes • Útero Amotara Zabelê. no sul da Bahia.</p>
    </div>
  </div>

</div>

app/views/pages/utero.html.erb
<div class="main-container">

  <div class="utero">
    <%= image_tag "Utero_Logo.png" %>
  </div>

  <div class="banner-utero">
    <%= image_tag "Utero-Terra.jpg" %>
  </div>

  <div class="utero-principios">
    <%= image_tag "U-Principios_Titulo.png" %>
    <div class="font-principios">
      <p><b>Útero</b> é o nome do conceito-guia que gerou, orienta, move o <b>ser-Zabelê</b> e suas realizações, como o <b>Universo Autônomo Intercultural de Saberes • Útero Amotara Zabelê.</b></p>
      <p>Representa a contínua geração, aprendizado e evolução da vida.</p>
      <p id="font-red-big">Útero é a experiência de vida.</p>
      <p><b> • nós com a Natureza e o Cosmo;</b><br><b> • saberes, fazeres e seres diversos;</b><br><b>• ancestralidade, presente e futuro;</b><br><b>• coletivo, ética e indivíduo;</b><b>• corpo, organismo e mente;</b><br><b>• ideias, palavras e atitudes.</b></p>
      <p id="font-red-big">Útero é a origem e integra 3 princípios.</p>
    </div>
  </div>

  <div class="decolonizacao">
    <%= image_tag "Decolonizacao_Tipo.png" %>
    <p id=decolonizacao><b>Interagindo, transformando, integrando o ser na diversidade e preparando o corpo-organismo-mente para uma nova experiência de vida.
    </b></p>
  </div>

  <div class="decolonizacao-vermelho">
    <%= image_tag "Decolonizacao_Titulo.png" %>
    <div class="font-deco">
      <p>Aprender para potencializar e evoluir o pensar, fazer e ser para, em coletivo, realizar um mundo melhor. Entendemos que precisamos nos libertar das certezas, abrir nossas mentes e corações para voltar a ouvir o outro e aprender com a diferença.</p>
      <p>Também questionar e redescobrir o caminho que nos trouxe até aqui para repensarmos nossos próximos passos. Acreditamos que uma troca de saberes que ultrapasse os limites e misture culturas, gêneros e etnicidades é o caminho para a evolução coletiva.</p>
      <p>  Queremos contribuir ativamente para desconstruir mitos que reforçam as desigualdades, o preconceito e criar um caminho de evolução do ser-humano na Terra que recupere nossa comunhão uns com os outros, com a Mãe Natureza e o Cosmo. Se o mundo pode ser mais harmônico para nós, precisamos realizá-lo juntos.</p>
      <p>Que a experiência Útero seja uma experiência libertadora e integradora do individual com
      o coletivo, da singularidade com a diversidade, do necessário com o possível, da consciência de“si” com o todo.</p>
    </div>
  </div>

  <div class="troca-saberes">
    <%= image_tag "TrocaSaberes_Tipo.png" %>
    <p id=decolonizacao><b>Conhecer outros pensares, fazeres e seres para conhecer a si mesmo.</b></p>
  </div>

  <div class="decolonizacao-vermelho"  id="azul">
    <%= image_tag "TrocaSaberes_Titulo.png" %>
    <div class="font-deco">
      <p>Acreditamos que o aprendizado só é possível pela interação entre múltiplos saberes. E que novos pontos de vista abrirão o caminho para um constante aprendizado sobre o mundo e sobre nós mesmos. Convivendo, conseguiremos coletivamente nos reconectar aos elementos essenciais que tornam a vida possível: amor, ética, respeito e comprometimento mútuo.</p>
      <p>A troca de saberes amplia, harmoniza e evolui a consciência ética de mundo, integrando o ser com a Realidade, a Natureza e o Universo; o indivíduo com a diversidade e o coletivo, o pensamento com a linguagem e as atitudes; as ideias com a realidade e suas consequências.</p>
      <p>Substancia o pensamento crítico, abrindo a mente para novas possibilidades de compreensão, ação, e realização de um mundo diverso, mais igualitário e com evolução comum.</p>

    </div>
  </div>

  <div class="mae-terra">
    <%= image_tag "RetornoMaeTerra_Tipo.png" %>
    <p id=decolonizacao><b>Conhecer outros pensares, fazeres e seres para conhecer a si mesmo.</b></p>
  </div>

  <div class="decolonizacao-vermelho"  id="verde">
    <%= image_tag "RetornoMaeTerra_Titulo.png" %>
    <div class="font-deco">
      <p>O Retorno à Mãe-Terra é a experiência orgânica-sensorial direta da cosmologia do Útero. Sua realização. Emerge do propósito de reintegrar o que vem sendo separado: o ser-humano da Natureza e o Cosmo, não só fisicamente como também essencialmente.</p>
      <p>Além do contato com a Natureza, o retorno também é uma metáfora para o processo real de reconexão com as origens (retorno ao útero, à essência do mundo e de si) e com os saberes ancestrais-universais.</p>
      <p>Em nossos projetos, como a Universidade Autômoma, buscamos proporcionar espaços e experiências de redescoberta e reconexão. De cada um de nós com o outro e de todos nós com a Mãe Terra.</p>

    </div>
  </div>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="movimenta-zabele">
    <%= image_tag "Movimenta_Picto-G.png", style: "height:10rem" %>
    <%= image_tag "MovimentaZabele_Tipo.png", style: 'height:6rem; padding-inline: 5%;' %>
    <div class="por-dentro" >
      <p>Fique por dentro de nossos projetos e atividades</p>
      <%= image_tag "Flecha_Picto.png", style: 'height:2rem' %>
    </div>
  </div>
  <div class="balls">
      <div class="blue-ball">
        <p id="font-1-ball">PARTICIPE DA
          REDE COLABORATIVA DE PROJETOS MULTICULTURAIS
          E EDUCACIONAIS LEVANTA ZABELÊ.</p>
        <p id="font-2-ball"></p> Qual a sua potência? Entre em contato
          e saiba como colaborar:
        <p><b>levantazabele@gmail.com</b>
          ou em nossas redes sociais.</p>
      </div>
    <div class="division-balls">
      <div class="green-ball">
        <p id="font-1-ball"><b>APOIE NOSSO CROWDFUNDING
        E A REALIZAÇÃO
        DO UNIVERSO ÚTERO AMOTARA ZABELÊ.</b></p>
      </div>
      <div class="black-ball">
        <p id="font-1-ball"><b>EMPRESAS, ENTIDADES CIVIS E INVESTIDORES, SEJAM NOSSO PARCEIRO NESSA JORNADA</b></p>
        <p id="font-2-ball">Entre em contato:
        <b>levantazabele@gmail.com</b></p>
      </div>
    </div>
  </div>
  <div class="icons">
    <%# <%= image_tag picto() %>
    <% case root_path %>
    <% when root_path %>
    <%= image_tag "Levanta-Zabele_Logo-Picto.png" %>
    <% when utero_path %>
    <%= image_tag "Utero_Logo-Picto.png" %>
    <% when "una"  %>
    <%= image_tag "Universo-Una_Logo-Picto.png" %>
    <% end %>
    <%= image_tag "Indicador-link-responsivo.png" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <div class="blocos">
    <div class= "navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "Levanta-Zabele_Logo-Picto.png" %>
      <% end %>
      <div class="indicator">
        <%= image_tag "Levanta-Zabele_Indicador-Link.png" %>
      </div>
      <%= link_to "/una", class: "navbar-brand" do %>
        <%= image_tag "Universo-Una_Logo-Picto.png" %>
      <% end %>
      <%= link_to "/utero", class: "navbar-brand" do %>
        <%= image_tag "Utero_Logo-Picto.png" %>
      <% end %>
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "Movimenta-Zabele_Picto.png" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "Contatoi_Picto.png" %>
    <% end %>
    <%= link_to "https://www.facebook.com/levantazabele", class: "navbar-brand", target: :_blanck do %>
      <%= image_tag "Facebook_Picto.png" %>
    <% end %>
    <%= link_to "https://instagram.com/levantazabele?igshid=YmMyMTA2M2Y=", class: "navbar-brand", target: :_blanck do %>
      <%= image_tag "Instagram_Picto.png" %>
    <% end %>
    <%= link_to " https://youtube.com/channel/UC1X7g771engFt8QdstDuQPw", class: "navbar-brand", target: :_blanck do %>
      <%= image_tag "YouTube_Picto.png" %>
    <% end %>
  </div>
  </div>
</div>